### ISSUE TITLE
[Crash] Game version 1.19

### ISSUE THREAD

**Issue by Cyan4235** [IoeCmcomc/MCDatapacker#12]
Changing the game version to 1.19 causes the program to restart as notified.  On restart the program crashes without an error or log.  Attempting to reopen it causes the window to flash up on screen, then crash again.

**Comment by IoeCmcomc** [comment]
Thanks for your report.
Since the app crashes when the game version is 1.19, you can use Registry Editor to set the game version manually (assuming you are on Windows).
1. Open the Registry Editor;
2. Go to `Computer\HKEY_CURRENT_USER\Software\IoeCmcomc\MCDatapacker\game` (or use Ctrl+F to find "MCDatapacker");
3. Change the `version` key to another version;
4. Re-run MCDatapacker.

**Comment by a-lakeside-viewer** [comment]
I would like to ask if there are any fixes to this issue if I'm using Ubuntu (Pop_OS, to be specific). After setting it to 1.19, the AppImage stopped working and would quickly load up a window before crashing if I tried running it. Couldn't find the directory (Software\IoeCmcomc\MCDatapacker\game) being referenced. I've searched both /etc and /bin as well as a quick Ctrl + F on my storage.
